name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '0 10 * * 5'

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php:
          - 7.4
          - 8.0
          - 8.1
          - 8.2
          - 8.3
        composer_args:
          - ''
          - '--prefer-stable --prefer-lowest'
        include:
          - php: 8.4
            composer_args: '--ignore-platform-req=php+'
    name: PHP ${{ matrix.php }} ${{ matrix.composer_args }}
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none
      - name: Build
        env:
          COMPOSER_ARGS: ${{ matrix.composer_args }}
        run: composer update --no-interaction --no-progress --prefer-dist $COMPOSER_ARGS
      - name: Lint
        run: vendor/bin/parallel-lint -e php,phpt --exclude tests/temp src tests
      - name: Tests
        run: vendor/bin/phpunit -c tests/phpunit.xml tests
      - name: PHPStan
        run: |
          vendor/bin/phpstan analyse -v
          vendor/bin/phpstan analyse -v -c phpstan.tests.neon.dist

  code_style:
    runs-on: ubuntu-latest
    needs: [ tests ]
    name: Code Style
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          coverage: none
      - name: Build
        run: composer update --no-interaction --no-progress --prefer-dist --prefer-stable
      - name: Check Code Style
        run: vendor/bin/phpcs

  code_coverage:
    runs-on: ubuntu-latest
    needs: [ tests ]
    continue-on-error: true
    name: Code Coverage
    steps:
      - uses: actions/checkout@v4
      - uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: xdebug
      - run: composer global require php-coveralls/php-coveralls
      - name: Build
        run: composer update --no-interaction --no-progress --prefer-dist --prefer-stable
      - name: Calculate coverage
        run: vendor/bin/phpunit -c tests/phpunit.xml --coverage-clover=coverage.xml --whitelist=src tests
      - name: Upload Coverage Report
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: php-coveralls --verbose --config tests/coveralls.yml
